basePath: /
definitions:
  api.ChannelsListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/sipapi.Channels'
        type: array
      total:
        type: integer
    type: object
  api.DevicesListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/sipapi.Devices'
        type: array
      total:
        type: integer
    type: object
  api.StreamsListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/sipapi.Streams'
        type: array
      total:
        type: integer
    type: object
  m.SysInfo:
    properties:
      addtime:
        type: integer
      cid:
        description: CID 通道id固定头部
        type: string
      cnum:
        description: CNUM 当前通道数
        type: integer
      did:
        description: DID 设备id固定头部
        type: string
      dnum:
        description: DNUM 当前设备数
        type: integer
      id:
        type: integer
      lid:
        description: LID 当前服务id
        type: string
      mediaServer:
        type: boolean
      region:
        description: Region 当前域
        type: string
      uptime:
        type: integer
    type: object
  sipapi.Channels:
    properties:
      active:
        description: Active 最后活跃时间
        type: integer
      address:
        description: Address ip地址
        type: string
      addtime:
        type: integer
      channelid:
        description: ChannelID 通道编码
        type: string
      civilcode:
        type: string
      deviceid:
        description: DeviceID 设备编号
        type: string
      fps:
        description: 视频FPS
        type: integer
      height:
        description: 视频高
        type: integer
      id:
        type: integer
      manufacturer:
        type: string
      memo:
        description: Memo 备注（用来标示通道信息）
        type: string
      model:
        type: string
      name:
        description: Name 通道名称（设备端设置名称）
        type: string
      owner:
        type: string
      parental:
        type: integer
      registerway:
        type: integer
      safetyway:
        type: integer
      secrecy:
        type: integer
      status:
        description: Status 状态  on 在线
        type: string
      streamtype:
        description: pull 媒体服务器主动拉流，push 监控设备主动推流
        type: string
      uptime:
        type: integer
      uri:
        type: string
      url:
        description: streamtype=pull时，拉流地址
        type: string
      vf:
        description: 视频编码格式
        type: string
      width:
        description: 视频宽
        type: integer
    type: object
  sipapi.Devices:
    properties:
      active:
        description: ActiveAt 最后心跳检测时间
        type: integer
      addtime:
        type: integer
      deviceid:
        description: DeviceID 设备id
        type: string
      devicetype:
        description: 设备类型DVR，NVR
        type: string
      firmware:
        description: Firmware 固件版本
        type: string
      host:
        description: Host Via 地址
        type: string
      id:
        type: integer
      manufacturer:
        description: Manufacturer 制造厂商
        type: string
      model:
        description: Model 型号
        type: string
      name:
        description: Name 设备名称
        type: string
      port:
        description: Port via 端口
        type: string
      proto:
        description: Proto 协议
        type: string
      pwd:
        description: PWD 密码
        type: string
      raddr:
        description: RAddr via recevied
        type: string
      region:
        description: Region 设备域
        type: string
      regist:
        description: Regist 是否注册
        type: boolean
      report:
        description: Rport via rport
        type: string
      source:
        description: Source
        type: string
      sysinfo:
        $ref: '#/definitions/m.SysInfo'
      transport:
        description: TransPort via transport
        type: string
      uptime:
        type: integer
      uri:
        type: string
    type: object
  sipapi.RecordDate:
    properties:
      date:
        description: 日期
        type: string
      items:
        description: 时间段
        items:
          $ref: '#/definitions/sipapi.RecordInfo'
        type: array
    type: object
  sipapi.RecordInfo:
    properties:
      end:
        type: integer
      start:
        type: integer
    type: object
  sipapi.Records:
    properties:
      daynum:
        description: 存在录像的天数
        type: integer
      list:
        items:
          $ref: '#/definitions/sipapi.RecordDate'
        type: array
      timenum:
        type: integer
    type: object
  sipapi.Streams:
    properties:
      addtime:
        type: integer
      callid:
        description: header callid
        type: string
      channelid:
        description: 通道ID
        type: string
      cseqno:
        type: integer
      deviceid:
        description: 设备ID
        type: string
      http:
        description: m3u8播放地址
        type: string
      id:
        type: integer
      msg:
        type: string
      rtmp:
        description: rtmp 播放地址
        type: string
      rtsp:
        description: rtsp 播放地址
        type: string
      status:
        description: 0正常 1关闭 -1 尚未开始
        type: integer
      stop:
        description: 是否停止
        type: boolean
      stream:
        description: zlm是否收到流
        type: boolean
      streamid:
        description: 视频流ID gb28181的ssrc
        type: string
      streamtype:
        description: pull 媒体服务器主动拉流，push 监控设备主动推流
        type: string
      t:
        description: 0  直播 1 历史
        type: integer
      uptime:
        type: integer
      wsflv:
        description: flv 播放地址
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: panjjo@vip.qq.com
    name: GoSIP
    url: https://github.com/panjjo/gosip
  description: GB28181 SIP服务端.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/panjjo/gosip
  title: GoSIP
  version: "2.0"
paths:
  /channels:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 可以根据查询条件查询通道列表
      parameters:
      - description: 条数(0-100) 默认20
        in: query
        name: limit
        type: integer
      - description: 间隔 默认0
        in: query
        name: skip
        type: integer
      - description: 排序,例:-key,根据key倒序,key,根据key正序
        in: query
        name: sort
        type: string
      - description: 查询条件,使用规则详情请看帮助
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/api.ChannelsListResponse'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 通道列表接口
      tags:
      - channels
  /channels/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除通道信息
      parameters:
      - description: 通道id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            type: string
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 通道删除接口
      tags:
      - channels
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 调整通道信息
      parameters:
      - description: 通道id
        in: path
        name: id
        required: true
        type: string
      - description: 通道备注
        in: formData
        name: memo
        type: string
      - description: 播放类型，pull 媒体服务器拉流，push 摄像头推流,默认push
        in: formData
        name: streamtype
        type: string
      - description: 静态拉流地址，streamtype=pull 时生效。
        in: formData
        name: url
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Channels'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 通道修改接口
      tags:
      - channels
  /channels/{id}/records:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 用来获取通道设备存储的可回放时间段列表，注意控制时间跨度，跨度越大，数据量越多，返回越慢，甚至会超时（最多10s）。
      parameters:
      - description: 通道id
        in: path
        name: id
        required: true
        type: string
      - description: 开始时间，时间戳
        in: query
        name: start
        required: true
        type: integer
      - description: 结束时间，时间戳
        in: query
        name: end
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Records'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 回放文件时间列表
      tags:
      - records
  /channels/{id}/streams:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 直播一个通道最多存在一个流，回放每请求一次生成一个流
      parameters:
      - description: 通道id
        in: path
        name: id
        required: true
        type: string
      - description: 是否回放，1回放，0直播，默认0
        in: formData
        name: replay
        type: integer
      - description: 回放开始时间，时间戳，replay=1时必传
        in: formData
        name: start
        type: integer
      - description: 回放结束时间，时间戳，replay=1时必传
        in: formData
        name: end
        type: integer
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Streams'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 监控播放（直播/回放）
      tags:
      - streams
  /devices:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 可以根据查询条件查询设备列表
      parameters:
      - description: 条数(0-100) 默认20
        in: query
        name: limit
        type: integer
      - description: 间隔 默认0
        in: query
        name: skip
        type: integer
      - description: 排序,例:-key,根据key倒序,key,根据key正序
        in: query
        name: sort
        type: string
      - description: 查询条件,使用规则详情请看帮助
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/api.DevicesListResponse'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 设备列表接口
      tags:
      - devices
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过此接口新增一个设备，获取设备id
      parameters:
      - description: 设备密码(GB28181认证密码)
        in: formData
        name: pwd
        required: true
        type: string
      - description: 设备名称
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Devices'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 设备新增接口
      tags:
      - devices
  /devices/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 删除设备信息
      parameters:
      - description: 设备id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            type: string
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 设备删除接口
      tags:
      - devices
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 调整设备信息
      parameters:
      - description: 设备id
        in: path
        name: id
        required: true
        type: string
      - description: 设备密码(GB28181认证密码)
        in: formData
        name: pwd
        type: string
      - description: 设备名称
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Devices'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 设备修改接口
      tags:
      - devices
  /devices/{id}/channels:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过此接口在设备下新增通道，获取通道id
      parameters:
      - description: 设备id
        in: path
        name: id
        required: true
        type: string
      - description: 通道备注
        in: formData
        name: memo
        type: string
      - description: 播放类型，pull 媒体服务器拉流，push 摄像头推流,默认push
        in: formData
        name: streamtype
        type: string
      - description: 静态拉流地址，streamtype=pull 时生效。
        in: formData
        name: url
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/sipapi.Channels'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 通道新增接口
      tags:
      - channels
  /streams:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 可以根据查询条件查询视频流列表
      parameters:
      - description: 条数(0-100) 默认20
        in: query
        name: limit
        type: integer
      - description: 间隔 默认0
        in: query
        name: skip
        type: integer
      - description: 排序,例:-key,根据key倒序,key,根据key正序
        in: query
        name: sort
        type: string
      - description: 查询条件,使用规则详情请看帮助
        in: query
        name: filters
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/api.StreamsListResponse'
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 视频流列表接口
      tags:
      - streams
  /streams/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 无人观看5分钟自动关闭，直播流无需调用此接口。
      parameters:
      - description: 流id,播放接口返回的streamid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            type: string
        "1000":
          description: ""
          schema:
            type: string
        "1001":
          description: ""
          schema:
            type: string
        "1002":
          description: ""
          schema:
            type: string
        "1003":
          description: ""
          schema:
            type: string
      summary: 停止播放（直播/回放）
      tags:
      - streams
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
